grant cib permissions
mozilla-platform-ops/relops_infra_as_code pull request #67
Opened 2021-03-25 07:05 UTC by grenade

associate contributor role with cib service principal

2021-03-25 16:42 UTC, dividehex requested changes

2021-03-25 16:42 UTC, dividehex commented on terraform/azure_ad/versions.tf
> +  features {}
Make sure enforce the tenant and sub id.  This prevent clobbering outside of the scope
```
  # FXCI Azure dev/test Subscription
  subscription_id = "108d46d5-fe9b-4850-9a7d-8c914aa6c1f0"
  tenant_id       = "c0dc8bb0-b616-427e-8217-9513964a145b"

2021-03-25 16:42 UTC, dividehex commented
Just add the tenant and sub ID.  LGTM otherwise.

2021-03-26 15:37 UTC, markcor commented
With as involved the configuration will be for each of these, I think we should compartmentalize each service into its own file.

2023-02-28 20:53 UTC, closed without merging